# US Military Deployments and Minority Communities {#minority-chapter}

This chapter provides supplementary information related to Chapter 4 of the book, focusing on how US military deployments interact with and are viewed by minority communities. 


```{r setup, warning=FALSE, message=FALSE, echo=FALSE}
library(tidyverse)
library(tidyr)
library(data.table)
library(job)
library(broom)
library(broom.mixed)
library(modelr)
library(cshapes)
library(countrycode)
library(dagitty)
library(ggdag)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(arm)
library(brms)
library(rstan)
library(cmdstanr)
library(parallel)
library(tidybayes)
library(scales)
library(ggdist)
library(ggh4x)
#library(ggtrack)
library(viridis)
library(kableExtra)
library(BayesPostEst)
library(texreg)
library(modelsummary)
library(gt)
library(webshot)
library(kableExtra)
library(ggExtra)
library(ggrepel)
library(ggmcmc)
library(ggpubr)
library(ggtext)
library(patchwork)
library(here)
library(performance)
library(tictoc)
library(sysfonts)
library(remotes)
library(formattable)
library(sparkline)
library(ltxsparklines)


knitr::opts_chunk$set(comment = '', dpi = 400, warning = FALSE, echo = FALSE, message = FALSE)

sysfonts::font_add_google("Oswald", family = "oswald")
showtext::showtext_auto()

# Set basesize for fonts in plots
basesize <- 11


# Regular plot theme
theme_flynn <- function(){ 
  
      theme_linedraw(base_size = basesize, base_family = "oswald") %+replace% 
        
        theme(plot.title = element_text(face = "bold", size = basesize * 1.3, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
              plot.subtitle = element_text(size = basesize),
              plot.caption = element_text(face = "italic", size = basesize * 0.6),
              panel.border = element_rect(fill = NA, size = 0.2),
              strip.background = element_rect(fill = "gray80", color = "black", size = 0.2),
              strip.text = element_text(size = basesize, color = "black", face = "bold", margin = margin(t = 0.2, b = 0.2, l = 0.2, r = 0.2, unit = "cm")),
              panel.background = element_rect(size = 0.2),
              panel.grid.major = element_line(color = "gray70", size = 0.15),
              panel.grid.minor = element_line(color = "gray90", size = 0.1),
              axis.title = element_text(face = "bold", size = basesize),
              axis.title.y = element_text(angle = 90, margin = margin(t = 0, r = 0.5, b = 0, l = 0, unit = "cm")),
              axis.title.x = element_text(margin = margin(t = 0.5, r = 0, b = 0, l = 0, unit = "cm")),
              axis.ticks = element_line(size = 0.1),
              axis.ticks.length = unit(0.1, "cm"),
              legend.title = element_text(size = basesize, face = "bold", hjust = 0, margin = margin(t = 0, b = 0, l = 0, r = 0, unit = "cm")),
              plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
              legend.margin = margin(t=-10, b=0, r=0, l=0),
              legend.box.margin = margin(-10,-10,-10,-10))
  }

# Map version of theme
theme_flynn_map <- function(){
  
  theme_void(base_family = "oswald") %+replace% 
    
    theme(plot.title = element_text(face = "bold", size = 18, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
          plot.subtitle = element_text(size = 12, hjust = 0, margin = margin(t = 0, b = 0.3, l = 0, r = 0, unit = "cm")),
          plot.caption = element_text(face = "italic", size = 8, hjust = 1, margin = margin(t = 0.2, unit = "cm")),
          strip.background = element_rect(fill = "gray80", color = "black"),
          strip.text = element_text(color = "black", face = "bold"),
          panel.grid.major = element_line(color = "white", size = 0),
          panel.grid.minor = element_line(color = "white", size = 0),
          #axis.title = element_text(face = "bold", size = 0),
          #axis.title.y = element_text(margin = margin(t = 0, r = 0.5, b = 0, l = 0, unit = "cm")),
          #axis.title.x = element_text(margin = margin(t = 0.5, r = 0, b = 0, l = 0, unit = "cm")),
          legend.title = element_text(face = "bold"),
          legend.position = "bottom",
          legend.key.height = unit(0.6, "cm"),
          legend.key.width = unit(2.5, "cm"))
}


ccode.list <- c("200", "210", "211", "230", "235", "255", "290", "325", "640", "690", "732", "740", "840", "900")


### Stan Setup ####

# Conflicted pckage really fucks things up
if(any(grepl("package:conflicted", search()))) detach("package:conflicted") else message("package conflicted not loaded")


# Parallelize machine
options(mc.cores = parallel::detectCores())
ncores <- parallel::detectCores()
rstan_options(auto_write = TRUE)


# Load opinion data for individual-level protest models.
load(here::here("../Book/Data/General", "opinion.data.RData")) 

# This fixes an encoding issue which duplicated the "Other" category unnecessarily. 
o.data <- setDT(o.data)[
  , relig := ifelse(grepl("Other", relig), "Other", relig)
]

set.seed(seed = 66502)


# Load model files because bookdown doesn't like something about reading the brms rds files in.

# Bivariate models for illustrative purposes
m.t1 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t1.rds"))
m.g1 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g1.rds"))
m.p1 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p1.rds"))

# Full models
m.t2 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t2.rds"))
m.g2 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g2.rds"))
m.p2 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p2.rds"))

# Models focusing on Japan
m.t2.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t2.japan.rds"))
m.g2.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g2.japan.rds"))
m.p2.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p2.japan.rds"))

m.t3 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t3.rds"))
m.g3 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g3.rds"))
m.p3 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p3.rds"))

m.t4 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t4.rds"))
m.g4 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g4.rds"))
m.p4 <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p4.rds"))

m.t4.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.t4.japan.rds"))
m.g4.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.g4.japan.rds"))
m.p4.japan <- readRDS(here::here("../Book/Output/Chapter-Minority/m.p4.japan.rds"))

priors.t <- brms::prior_summary(m.t1) 
priors.g <- brms::prior_summary(m.g1)
priors.p <- brms::prior_summary(m.p1)

priors.t2 <- brms::prior_summary(m.t2) 
priors.g2 <- brms::prior_summary(m.g2)
priors.p2 <- brms::prior_summary(m.p2)

priors.t2.japan <- brms::prior_summary(m.t2.japan) 
priors.g2.japan <- brms::prior_summary(m.g2.japan)
priors.p2.japan <- brms::prior_summary(m.p2.japan)

```


## Descriptive Information

```{r minority-description, echo=FALSE, warning=FALSE, message=FALSE}

# Minorities as a percent of the sample by year
# # Note that I had to edit this code chunk and changed the `length(X1)` line relative tot he original code because the original code was spitting back "1" for the observation count for 2020 for all countries. No idea why.
minperc <- o.data %>% 
  group_by(country, year) %>% 
  mutate(minority.yes = ifelse(minority == "Yes", 1, 0),
         groupobs = length(X1)) %>% 
  dplyr::summarise(minority = sum(minority.yes, na.rm = TRUE),
            obs = mean(groupobs, na.rm = TRUE)) %>% 
  mutate(min.per = minority/obs) %>% 
  filter(!is.na(country))

ggplot(minperc, aes(y = factor(year), x = min.per, color = country)) +
  geom_text(aes(label = country), position = position_jitter(height = 0.4), size = 2.5) +
  theme_flynn() +
  scale_x_continuous(labels = scales::percent_format()) +
  guides(color = FALSE) +
  theme(plot.title.position = "plot") +
  labs(x = "Percent",
       y = "Year",
       color = "Country",
       title = "Self-identified minority group members as percent of country sample")

```


### Prior Specification Tables for Minority Models

```{r prior-info-crime-troops, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.t, caption = "Priors specifications for bivariate Troops contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-gov, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.g, caption = "Priors specifications for bivariate Government contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-people, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.p, caption = "Priors specifications for bivariate People contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-troops-2, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.t2, caption = "Priors specifications for full Troops contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-gov-2, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.g2, caption = "Priors specifications for full Government contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-people-2, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.p2, caption = "Priors specifications for full People contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-troops-japan, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.t2.japan, caption = "Priors specifications for full Japan Troops contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-gov-japan, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.g2.japan, caption = "Priors specifications for full Japan Government contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```

```{r prior-info-crime-people-japan, warning=FALSE, echo=FALSE, message=FALSE}

kableExtra::kable(priors.p2.japan, caption = "Priors specifications for full Japan People contact models.", digits = 3) |> 
  kableExtra::kable_styling(font_size = 11) |> 
  kableExtra::scroll_box(height = "400px", width = "100%")

```




### Posterior Predictive Check Figures

```{r posterior-check-crime-troops, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for bivariate contact models and attitudes towards the US troops outcome variable."}
check.t <- brms::pp_check(m.t1, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Troops Model")

check.t

```

```{r posterior-check-crime-gov, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for bivariate contact models and attitudes towards the US government outcome variable."}
check.g <- brms::pp_check(m.g1, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Government Model")

check.g

```


```{r posterior-check-crime-people, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for bivaraite contact models and attitudes towards the US people outcome variable."}
check.p <- brms::pp_check(m.p1, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for People Model")

check.p

```




```{r posterior-check-crime-troops-2, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for full contact models and attitudes towards the US troops outcome variable."}
check.t2 <- brms::pp_check(m.t2, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Troops Model")

check.t2

```

```{r posterior-check-crime-gov-2, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for full contact models and attitudes towards the US government outcome variable."}
check.g2 <- brms::pp_check(m.g2, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Government Model")

check.g2

```


```{r posterior-check-crime-people-2, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for full contact models and attitudes towards the US people outcome variable."}
check.p2 <- brms::pp_check(m.p2, nsamples = 100, type = "bars_grouped", group = "country") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for People Model")

check.p2

```






```{r posterior-check-crime-troops-2-japan, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for contact models and attitudes towards the US troops outcome variable. Models look at Japan only and contain varying effects for minority status across provinces."}
check.t2.japan <- brms::pp_check(m.t2.japan, nsamples = 100, type = "bars_grouped", group = "province") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Troops Model")

check.t2.japan

```

```{r posterior-check-crime-gov-2-japan, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for contact models and attitudes towards the US government outcome variable. Models look at Japan only and contain varying effects for minority status across provinces."}
check.g2.japan <- brms::pp_check(m.g2.japan, nsamples = 100, type = "bars_grouped", group = "province") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for Government Model")

check.g2.japan

```


```{r posterior-check-crime-people-2-japan, echo=FALSE, warning=FALSE, message=FALSE, fig.cap="Posterior predictive checks for contact models and attitudes towards the US people outcome variable. Models look at Japan only and contain varying effects for minority status across provinces."}
check.p2.japan <- brms::pp_check(m.p2.japan, nsamples = 100, type = "bars_grouped", group = "province") +
  theme_flynn() +
  labs(title = "Posterior Predictive Check for People Model")

check.p2.japan

```


